WebsiteBanSach/WebSiteBanSach/WebSiteBanSach/Models/THELOAI.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THELOAI
    {
        public THELOAI()
        {
            this.SACHes = new HashSet<SACH>();
        }
    
        public int MATHELOAI { get; set; }
        public string TENTHELOAI { get; set; }
    
        public virtual ICollection<SACH> SACHes { get; set; }
    }
}

WebsiteBanSach/WebSiteBanSach/WebSiteBanSach/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;
using PagedList;
namespace WebSiteBanSach.Controllers
{
    public class SachController : Controller
    {
        //
        // GET: /Sach/
        QL_SACHEntities1 db = new QL_SACHEntities1();
        public ActionResult SachPartial(int? page)
        {
            var ListSach = db.SACHes.OrderBy(cd => cd.TENSACH).ToList();


            // 2. Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;

            // 3. Tạo truy vấn, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            // theo LinkID mới có thể phân trang.
            var links = (from l in db.SACHes
                         select l).OrderBy(x => x.MASACH);

            // 4. Tạo kích thước trang (pageSize) hay là số Link hiển thị trên 1 trang
            int pageSize = 8;

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // 5. Trả về các Link được phân trang theo kích thước và số trang.
            return View(links.ToPagedList(pageNumber, pageSize));

        }
        public ActionResult XemChiTiet(int ms)
        {
            SACH SP = db.SACHes.Single(s => s.MASACH == ms);
            if (SP == null)
            {
                return HttpNotFound();
            }
            return View(SP);
        }
        [HttpPost]
        public ActionResult SachPartial(int? page,FormCollection f)
        {
            var ten = f["timkiem"];
            var ListSach = db.SACHes.Where(x => x.TENSACH.Contains(ten)).ToList();
            // 2. Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;

            // 3. Tạo truy vấn, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            // theo LinkID mới có thể phân trang.
            var links = (from l in db.SACHes.Where(x => x.TENSACH.Contains(ten))
                         select l).OrderBy(x => x.MASACH);

            // 4. Tạo kích thước trang (pageSize) hay là số Link hiển thị trên 1 trang
            int pageSize = 8;

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // 5. Trả về các Link được phân trang theo kích thước và số trang.
            return View(links.ToPagedList(pageNumber, pageSize));
     

        }
        

    }
}

WebsiteBanSach/WebSiteBanSach/WebSiteBanSach/Controllers/TacGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;

namespace WebSiteBanSach.Controllers
{
    public class TacGiaController : Controller
    {
        QL_SACHEntities1 db = new QL_SACHEntities1();

        public ActionResult TacGiaPartial()
        {
            var ListTG = db.TACGIAs.OrderBy(tg => tg.MATG).Take(5).ToList();
            return View(ListTG);
        }

        public ViewResult SachTheoTG(int maTG)
        {
            var ListSach = db.SACHes.Where(s => s.MATACGIA == maTG).ToList();
            TACGIA tg = db.TACGIAs.Single(t => t.MATG == maTG);
            ViewBag.TG = tg.TENTG;
            if (ListSach.Count == 0)
            {
                ViewBag.Sach = "Không có sách nào thuộc tác giả này !";
            }
            return View(ListSach);

        }
    }
}

WebsiteBanSach/WebSiteBanSach/WebSiteBanSach/Controllers/TheLoaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;
namespace WebSiteBanSach.Controllers
{
    public class TheLoaiController : Controller
    {
        //
        // GET: /TheLoai/
        QL_SACHEntities1 db = new QL_SACHEntities1();
        public ActionResult TheLoaiPartial()
        {
            var ListTheLoai = db.THELOAIs.Take(10).OrderBy(cd => cd.TENTHELOAI).ToList();

            return View(ListTheLoai);
        }

        public ViewResult SachTheoTL(int ms)
        {
            var ListSach = db.SACHes.Where(s => s.MATHELOAI == ms).OrderBy(s => s.GIABAN).ToList();
            THELOAI tl = db.THELOAIs.Single(TL => TL.MATHELOAI == ms);
            ViewBag.TL = tl.TENTHELOAI;
            if (ListSach.Count == 0)
            {
                ViewBag.Sach = "Không có sách nào thuộc thể loại nào !";
            }
            return View(ListSach);
        }

    }
}

WebsiteBanSach/WebSiteBanSach/WebSiteBanSach/Views/TheLoai/SachTheoTL.cshtml
@using WebSiteBanSach.Models;
@model List<SACH>

@{
    ViewBag.Title = "SachTheoTL";
    Layout = "~/Views/Shared/PageLayout.cshtml";
}
@*<div class="row" style="padding-top: 1%">
    <div class="col-3" style="padding: 0">
        @Html.Action("TheLoaiPartial", "TheLoai")
        @Html.Action("TacGiaPartial", "TacGia")
    </div>*@
@* <div class="col-9">*@
<style>
    .content {
    }
    .image {

    }
    .text {
        bottom:0px;
        text-align:center;
        position:absolute;
        color:red;
        text-decoration:none;
        opacity:0;
        width:200px;
        height:250px;
    }
        .content:hover .image{
            opacity:0.1;
        }
    .content:hover .text {
        opacity:1;
    }
</style>
<center><h2 style="text-transform:uppercase">SÁCH THEO THỂ LOẠI @ViewBag.TL</h2></center>
@ViewBag.Sach
<div class="row">
    @{
            
        foreach (var item in Model)
        {
        <div class="col-4">
            <a href="@Url.Action("XemChiTiet","Sach", new { @ms = item.MASACH })" class="content">
                        <div class="text">
                            <span><strong title="@item.MOTA">@item.MOTA.Substring(0, 40)...</strong></span><br />
                            <span>Xem chi tiết</span> 
                        </div>
                        
                        
                        <img class="image" src="@Url.Content("~/Images/sanpham/" + item.HINH)" width="200px" height="250px"/>

                    </a> 
            @if (item.TENSACH.Length > 20)
            {
                <p>
                    <strong title="@item.TENSACH">@item.TENSACH.Substring(0, 20)...</strong><br />
                    @*<a style="color:blue;text-decoration:none"  href="@Url.Action("XemChiTiet", "Sach", new { @ms = item.MASACH })">Chi Tiết</a>*@
                </p>
            }
            else
            {
                <p>
                    <strong title="@item.TENSACH">@item.TENSACH</strong><br />
                    @*<a style="color:blue;text-decoration:none" href="@Url.Action("XemChiTiet", "Sach", new { @ms = item.MASACH })">Chi Tiết</a>*@
                </p>
                <div class="clear"></div>
            }
            <div class="row">
                <div class="col">
                    <b class="" style="color: red; font-size: 22px;">@item.THANHTIEN <sup style="font-size: 10px">VNĐ</sup></b>
                    <strike class="">@item.GIABAN</strike>
                    <span class="" style="color: red">-@item.GIAMGIA%</span>
                </div>
            </div>
        </div>
        }   
    }
</div>
@*    </div>*@
@*</div>*@

WebsiteBanSach/WebSiteBanSach/WebSiteBanSach/Views/TheLoai/TheLoaiPartial.cshtml
@using WebSiteBanSach.Models;
@model List<THELOAI>
<ul class="list-group list-group-flush text-left">
    <li class="list-group-item" style="background-color: #3c3c2a;"><a href="#" style="text-transform: uppercase; text-decoration: none; color: white; font-weight: bold;">Thể Loại Sách</a></li>
    @{
        foreach (var item in Model)
        {
        <li class="list-group-item">
            <a href="@Url.Action("SachTheoTL", "TheLoai", new { @ms = item.MATHELOAI })" style="text-transform:uppercase; text-decoration:none; color: #3c3c2a">@item.TENTHELOAI </a>
        </li>
        }                   
        <li class="list-group-item"><a href="#" style="text-transform: uppercase; text-decoration: none;"></a></li>
    }

</ul>